/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  description?: string;
  category?: string;
  image?: string;
  views?: number;
  likes?: number;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  username?: string;
  image?: string;
  email?: string;
  bio?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Post | Author | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: GET_ALL_POSTS_QUERY_DESC
// Query: *[    _type == "post" &&    defined(slug.current) &&    (      !defined($search) ||      category match $search ||      title match $search ||      description match $search ||      author->username match $search ||      author->_id match $search ||      author->name match $search    )  ] | order(_createdAt desc) [$start...$end] {    _id,    _createdAt,    title,    "slug": slug.current,    category,    description,    image,    likes,    views,    "author": author -> {      _id,      username,      name,      image    },  }
export type GET_ALL_POSTS_QUERY_DESCResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: string | null;
  category: string | null;
  description: string | null;
  image: string | null;
  likes: number | null;
  views: number | null;
  author: {
    _id: string;
    username: string | null;
    name: string | null;
    image: string | null;
  } | null;
}>;
// Variable: GET_POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug && author->username == $username][0] {  _id,  title,  description,  category,  image,  likes,  author -> {  username,  name,  image  },  views,  _createdAt,  _updatedAt,  content}
export type GET_POST_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  description: string | null;
  category: string | null;
  image: string | null;
  likes: number | null;
  author: {
    username: string | null;
    name: string | null;
    image: string | null;
  } | null;
  views: number | null;
  _createdAt: string;
  _updatedAt: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
} | null;
// Variable: GET_USER_BY_USERNAME_QUERY
// Query: *[_type == "author" && username == $username][0]
export type GET_USER_BY_USERNAME_QUERYResult = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  username?: string;
  image?: string;
  email?: string;
  bio?: string;
} | null;
// Variable: GET_AUTHOR_ID_BY_USERNAME_QUERY
// Query: *[_type == "author" && username == $username][0] {  _id,}
export type GET_AUTHOR_ID_BY_USERNAME_QUERYResult = {
  _id: string;
} | null;
// Variable: GET_USER_POSTS_QUERY
// Query: *[_type == "post" && author->username == $username] | order(_createdAt desc) {  _id,  _createdAt,  title,  "slug": slug.current,  category,  description,  image,  likes,  views,  "author": author -> {    _id,    username,    name,    image  },}
export type GET_USER_POSTS_QUERYResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: string | null;
  category: string | null;
  description: string | null;
  image: string | null;
  likes: number | null;
  views: number | null;
  author: {
    _id: string;
    username: string | null;
    name: string | null;
    image: string | null;
  } | null;
}>;
// Variable: GET_IMAGE_REF_BY_ID
// Query: *[_type == "post" && _id == $postId][0].image.asset._ref
export type GET_IMAGE_REF_BY_IDResult = null;
// Variable: CHECK_USER_LIKED_POST
// Query: count(*[_type == "like" && author._ref == $authorId && post._ref == $postId]) > 0
export type CHECK_USER_LIKED_POSTResult = boolean;
// Variable: GET_COMMENTS_BY_POST
// Query: *[_type == "comment" && post._ref == $postId] | order(_createdAt desc) {        _id,        _createdAt,        text,        "author": author -> {            username,            name,            image        }    }
export type GET_COMMENTS_BY_POSTResult = Array<never>;
// Variable: GET_COMMENT_COUNT_BY_POST
// Query: count(*[_type == "comment" && post._ref == $postId])
export type GET_COMMENT_COUNT_BY_POSTResult = number;
// Variable: GET_ALL_CATEGORIES
// Query: array::unique(*[_type == "post" && defined(category) && defined(slug.current)].category)
export type GET_ALL_CATEGORIESResult = Array<string | null>;
// Variable: GET_POSTS_BY_CATEGORY
// Query: *[_type == "post" && category == $category && defined(slug.current)] | order(_createdAt desc) [$start...$end] {        _id,        _createdAt,        title,        "slug": slug.current,        category,        description,        image,        likes,        views,        "author": author -> {            _id,            username,            name,            image        }    }
export type GET_POSTS_BY_CATEGORYResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: string | null;
  category: string | null;
  description: string | null;
  image: string | null;
  likes: number | null;
  views: number | null;
  author: {
    _id: string;
    username: string | null;
    name: string | null;
    image: string | null;
  } | null;
}>;
// Variable: GET_TOTAL_POSTS_BY_CATEGORY
// Query: count(*[_type == "post" && category == $category && defined(slug.current)])
export type GET_TOTAL_POSTS_BY_CATEGORYResult = number;
// Variable: GET_RELATED_POSTS
// Query: *[_type == "post" && category == $category && _id != $postId && defined(slug.current)] | order(_createdAt desc) [0...3] {        _id,        _createdAt,        title,        "slug": slug.current,        category,        description,        image,        likes,        views,        "author": author -> {            _id,            username,            name,            image        }    }
export type GET_RELATED_POSTSResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: string | null;
  category: string | null;
  description: string | null;
  image: string | null;
  likes: number | null;
  views: number | null;
  author: {
    _id: string;
    username: string | null;
    name: string | null;
    image: string | null;
  } | null;
}>;
// Variable: GET_LATEST_POSTS_FOR_RSS
// Query: *[_type == "post" && defined(slug.current)] | order(_createdAt desc) [0...20] {        _id,        _createdAt,        title,        "slug": slug.current,        description,        category,        "authorUsername": author->username    }
export type GET_LATEST_POSTS_FOR_RSSResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  category: string | null;
  authorUsername: string | null;
}>;
// Variable: GET_TOTAL_POSTS_COUNT
// Query: count(*[    _type == "post" &&    defined(slug.current) &&    (      !defined($search) ||      title match $search ||      category match $search ||      description match $search ||      author->username match $search ||      author->name match $search    )  ])
export type GET_TOTAL_POSTS_COUNTResult = number;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[\n    _type == \"post\" &&\n    defined(slug.current) &&\n    (\n      !defined($search) ||\n      category match $search ||\n      title match $search ||\n      description match $search ||\n      author->username match $search ||\n      author->_id match $search ||\n      author->name match $search\n    )\n  ] | order(_createdAt desc) [$start...$end] {\n    _id,\n    _createdAt,\n    title,\n    \"slug\": slug.current,\n    category,\n    description,\n    image,\n    likes,\n    views,\n    \"author\": author -> {\n      _id,\n      username,\n      name,\n      image\n    },\n  }\n": GET_ALL_POSTS_QUERY_DESCResult;
    "*[_type == \"post\" && slug.current == $slug && author->username == $username][0] {\n  _id,\n  title,\n  description,\n  category,\n  image,\n  likes,\n  author -> {\n  username,\n  name,\n  image\n  },\n  views,\n  _createdAt,\n  _updatedAt,\n  content\n}": GET_POST_BY_SLUG_QUERYResult;
    "*[_type == \"author\" && username == $username][0]": GET_USER_BY_USERNAME_QUERYResult;
    "*[_type == \"author\" && username == $username][0] {\n  _id,}": GET_AUTHOR_ID_BY_USERNAME_QUERYResult;
    "*[_type == \"post\" && author->username == $username] | order(_createdAt desc) {\n  _id,\n  _createdAt,\n  title,\n  \"slug\": slug.current,\n  category,\n  description,\n  image,\n  likes,\n  views,\n  \"author\": author -> {\n    _id,\n    username,\n    name,\n    image\n  },\n}": GET_USER_POSTS_QUERYResult;
    "*[_type == \"post\" && _id == $postId][0].image.asset._ref": GET_IMAGE_REF_BY_IDResult;
    "count(*[_type == \"like\" && author._ref == $authorId && post._ref == $postId]) > 0": CHECK_USER_LIKED_POSTResult;
    "\n    *[_type == \"comment\" && post._ref == $postId] | order(_createdAt desc) {\n        _id,\n        _createdAt,\n        text,\n        \"author\": author -> {\n            username,\n            name,\n            image\n        }\n    }\n": GET_COMMENTS_BY_POSTResult;
    "count(*[_type == \"comment\" && post._ref == $postId])": GET_COMMENT_COUNT_BY_POSTResult;
    "\n    array::unique(*[_type == \"post\" && defined(category) && defined(slug.current)].category)\n": GET_ALL_CATEGORIESResult;
    "\n    *[_type == \"post\" && category == $category && defined(slug.current)] | order(_createdAt desc) [$start...$end] {\n        _id,\n        _createdAt,\n        title,\n        \"slug\": slug.current,\n        category,\n        description,\n        image,\n        likes,\n        views,\n        \"author\": author -> {\n            _id,\n            username,\n            name,\n            image\n        }\n    }\n": GET_POSTS_BY_CATEGORYResult;
    "\n    count(*[_type == \"post\" && category == $category && defined(slug.current)])\n": GET_TOTAL_POSTS_BY_CATEGORYResult;
    "\n    *[_type == \"post\" && category == $category && _id != $postId && defined(slug.current)] | order(_createdAt desc) [0...3] {\n        _id,\n        _createdAt,\n        title,\n        \"slug\": slug.current,\n        category,\n        description,\n        image,\n        likes,\n        views,\n        \"author\": author -> {\n            _id,\n            username,\n            name,\n            image\n        }\n    }\n": GET_RELATED_POSTSResult;
    "\n    *[_type == \"post\" && defined(slug.current)] | order(_createdAt desc) [0...20] {\n        _id,\n        _createdAt,\n        title,\n        \"slug\": slug.current,\n        description,\n        category,\n        \"authorUsername\": author->username\n    }\n": GET_LATEST_POSTS_FOR_RSSResult;
    "\n  count(*[\n    _type == \"post\" &&\n    defined(slug.current) &&\n    (\n      !defined($search) ||\n      title match $search ||\n      category match $search ||\n      description match $search ||\n      author->username match $search ||\n      author->name match $search\n    )\n  ])\n": GET_TOTAL_POSTS_COUNTResult;
  }
}
